apiVersion: apps/v1 
kind: Deployment
metadata:
  name: blue-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      name: orange-deployment
  template:
    metadata:
      labels:
        name: orange-deployment
    spec: 
      containers:
      - name: orange-deployment
        image: adamtravis/rollouts:orange
        # orange, green, Orange
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata: 
  name: orange-deployment
  labels:
    name: orange-deployment
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
  selector:
    name: green-deployment
  type: LoadBalancer
